import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db, auth } from './firebase';
import { encryptData } from './encryption';

export async function backupData(type: string, data: any) {
  if (!auth.currentUser) return;

  try {
    // Encrypt the sensitive payload before storage
    const encryptedPayload = encryptData(data);

    await addDoc(collection(db, 'backups'), {
      type,
      payload: encryptedPayload,
      userId: auth.currentUser.uid,
      timestamp: serverTimestamp(),
      autoGenerated: true,
      encrypted: true
    });
    console.log(`[Backup System] ${type} backed up with advanced encryption.`);
  } catch (error) {
    console.error(`[Backup System] Error backing up ${type}:`, error);
  }
}
