import { useState, useEffect } from 'react';
import { collection, query, where, orderBy, onSnapshot, addDoc, serverTimestamp, getDocs, deleteDoc, doc, writeBatch } from 'firebase/firestore';
import { db, auth } from '../lib/firebase';
import { decryptData, encryptData, encryptNumeric } from '../lib/encryption';
import { useCompany } from '../context/CompanyContext';
import { Database, Download, RotateCcw, Trash2, Clock, ShieldCheck, AlertTriangle, CheckCircle2, Search } from 'lucide-react';
import { format } from 'date-fns';
import { fr } from 'date-fns/locale';
import { motion, AnimatePresence } from 'motion/react';
import { cn } from '../lib/utils';

interface BackupRecord {
  id: string;
  type: string;
  payload: string;
  timestamp: any;
  autoGenerated: boolean;
  encrypted: boolean;
}

export default function Backups() {
  const { selectedCompany, revenues, detailedEntries, transactions, budgets, goal } = useCompany();
  const [backups, setBackups] = useState<BackupRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [isBackingUp, setIsBackingUp] = useState(false);
  const [backupStatus, setBackupStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [restoringId, setRestoringId] = useState<string | null>(null);
  const [restoreStep, setRestoreStep] = useState<string>('');
  const [restoreStatus, setRestoreStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    if (!auth.currentUser) return;

    const q = query(
      collection(db, 'backups'),
      where('userId', '==', auth.currentUser.uid),
      orderBy('timestamp', 'desc')
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      setBackups(snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as BackupRecord)));
      setLoading(false);
    });

    return () => unsubscribe();
  }, []);

  const handleManualBackup = async () => {
    if (!auth.currentUser || !selectedCompany) return;
    setIsBackingUp(true);
    setBackupStatus('idle');

    try {
      const snapData = {
        companyId: selectedCompany.id,
        companyName: selectedCompany.name,
        revenues,
        detailedEntries,
        transactions,
        budgets,
        goal,
        snapshotDate: new Date().toISOString()
      };

      const encryptedPayload = encryptData(snapData);

      await addDoc(collection(db, 'backups'), {
        type: 'MANUAL_FULL_SNAPSHOT',
        payload: encryptedPayload,
        userId: auth.currentUser.uid,
        timestamp: serverTimestamp(),
        autoGenerated: false,
        encrypted: true
      });

      setBackupStatus('success');
      setTimeout(() => setBackupStatus('idle'), 3000);
    } catch (error) {
      console.error('Backup error:', error);
      setBackupStatus('error');
      setTimeout(() => setBackupStatus('idle'), 5000);
    } finally {
      setIsBackingUp(false);
    }
  };

  const handleRestore = async (backup: BackupRecord) => {
    if (!auth.currentUser || !selectedCompany) return;
    
    const confirmRestore = confirm(
      "ATTENTION: La restauration remplacera vos données actuelles (Revenus, Dépenses, Transactions, Budgets, Objectifs) par celles de la sauvegarde pour cette entreprise. Cette action est irréversible. Voulez-vous continuer ?"
    );
    
    if (!confirmRestore) return;

    setRestoringId(backup.id);
    setRestoreStatus('idle');
    setRestoreStep('Initialisation...');

    try {
      setRestoreStep('Déchiffrement des données...');
      const data = decryptData<any>(backup.payload);
      if (!data) throw new Error('Impossible de décrypter la sauvegarde.');

      const batch = writeBatch(db);

      // 1. Clear existing data for this company
      setRestoreStep('Nettoyage des données actuelles...');
      
      const collectionsToClear = ['revenues', 'detailed_entries', 'transactions', 'budgets', 'goals'];
      for (const collName of collectionsToClear) {
        const snap = await getDocs(query(
          collection(db, collName), 
          where('userId', '==', auth.currentUser.uid), 
          where('companyId', '==', selectedCompany.id)
        ));
        snap.docs.forEach(d => batch.delete(d.ref));
      }

      // 2. Add restored revenues
      setRestoreStep('Restauration des revenus...');
      if (data.revenues && Array.isArray(data.revenues)) {
        data.revenues.forEach((rev: any) => {
          const { id, ...cleanRev } = rev;
          const restoredRev = {
            ...cleanRev,
            revenue: encryptNumeric(cleanRev.revenue),
            userId: auth.currentUser!.uid,
            createdAt: serverTimestamp(),
            isEncrypted: true
          };
          const docRef = doc(collection(db, 'revenues'));
          batch.set(docRef, restoredRev);
        });
      }

      // 3. Add restored detailed entries
      setRestoreStep('Restauration des dépenses détaillées...');
      if (data.detailedEntries && Array.isArray(data.detailedEntries)) {
        data.detailedEntries.forEach((entry: any) => {
          const { id, date, ...cleanEntry } = entry;
          
          const encryptedBreakdown: any = {};
          Object.entries(cleanEntry.breakdown || {}).forEach(([k, v]) => {
            encryptedBreakdown[k] = encryptNumeric(v as number);
          });

          const restoredEntry = {
            ...cleanEntry,
            breakdown: encryptedBreakdown,
            total: encryptNumeric(cleanEntry.total),
            userId: auth.currentUser!.uid,
            date: serverTimestamp(),
            isEncrypted: true
          };
          
          const docRef = doc(collection(db, 'detailed_entries'));
          batch.set(docRef, restoredEntry);
        });
      }

      // 4. Add restored transactions
      setRestoreStep('Restauration des transactions...');
      if (data.transactions && Array.isArray(data.transactions)) {
        data.transactions.forEach((trans: any) => {
          const { id, date, createdAt, ...cleanTrans } = trans;
          const restoredTrans = {
            ...cleanTrans,
            amount: encryptNumeric(cleanTrans.amount || 0),
            status: cleanTrans.status || 'pending',
            date: date instanceof Date ? date : (date?.toDate ? date.toDate() : new Date(date)),
            userId: auth.currentUser!.uid,
            createdAt: serverTimestamp(),
            isEncrypted: true
          };
          const docRef = doc(collection(db, 'transactions'));
          batch.set(docRef, restoredTrans);
        });
      }

      // 5. Add restored budgets
      setRestoreStep('Restauration des budgets...');
      if (data.budgets && Array.isArray(data.budgets)) {
        data.budgets.forEach((budget: any) => {
          const { id, createdAt, updatedAt, ...cleanBudget } = budget;
          const restoredBudget = {
            ...cleanBudget,
            targetRevenue: encryptNumeric(cleanBudget.targetRevenue || 0),
            expenseLimit: encryptNumeric(cleanBudget.expenseLimit || 0),
            userId: auth.currentUser!.uid,
            updatedAt: serverTimestamp(),
            isEncrypted: true
          };
          const docRef = doc(collection(db, 'budgets'));
          batch.set(docRef, restoredBudget);
        });
      }

      // 6. Add restored goal
      setRestoreStep('Restauration des objectifs...');
      if (data.goal) {
        const { id, updatedAt, ...cleanGoal } = data.goal;
        const restoredGoal = {
          ...cleanGoal,
          monthlyGoal: encryptNumeric(cleanGoal.monthlyGoal || 0),
          yearlyGoal: encryptNumeric(cleanGoal.yearlyGoal || 0),
          userId: auth.currentUser!.uid,
          updatedAt: serverTimestamp(),
          isEncrypted: true
        };
        const docRef = doc(collection(db, 'goals'));
        batch.set(docRef, restoredGoal);
      }

      setRestoreStep('Finalisation de la transaction...');
      await batch.commit();
      setRestoreStatus('success');
      setRestoreStep('Restauration réussie !');
      setTimeout(() => {
        setRestoreStatus('idle');
        setRestoringId(null);
      }, 3000);
    } catch (error) {
      console.error('Restore error:', error);
      setRestoreStatus('error');
      setRestoreStep('Échec de la restauration.');
      setTimeout(() => {
        setRestoreStatus('idle');
        setRestoringId(null);
      }, 5000);
    }
  };

  const handleDeleteBackup = async (id: string) => {
    if (!confirm('Supprimer cette sauvegarde définitivement ?')) return;
    try {
      await deleteDoc(doc(db, 'backups', id));
    } catch (error) {
      console.error('Delete error:', error);
    }
  };

  const filteredBackups = backups.filter(b => 
    b.type.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-8 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-6">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-secondary font-bold text-[10px] uppercase tracking-[0.2em]">
            <RotateCcw size={14} />
            <span>Sécurité & Intégrité</span>
          </div>
          <h1 className="font-display font-bold text-3xl sm:text-4xl text-on-surface">Sauvegardes & Restauration</h1>
          <p className="text-on-surface-variant text-sm font-sans opacity-70">
            Gérez vos archives chiffrées et recupérez vos données en cas de besoin.
          </p>
        </div>
        <button 
          onClick={handleManualBackup}
          disabled={isBackingUp}
          className={cn(
            "flex items-center gap-3 px-8 py-4 rounded-2xl font-bold transition-all shadow-xl disabled:opacity-50",
            backupStatus === 'success' ? "bg-emerald-500 text-white shadow-emerald-500/20" :
            backupStatus === 'error' ? "bg-red-500 text-white shadow-red-500/20" :
            "bg-primary-container text-white shadow-primary-container/20 hover:brightness-110 active:scale-95"
          )}
        >
          {isBackingUp ? (
            <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
          ) : backupStatus === 'success' ? (
            <CheckCircle2 size={20} />
          ) : backupStatus === 'error' ? (
            <AlertTriangle size={20} />
          ) : (
            <Download size={20} />
          )}
          <span>
            {isBackingUp ? 'Sauvegarde en cours...' : 
             backupStatus === 'success' ? 'Sauvegardé !' : 
             backupStatus === 'error' ? 'Échec' : 'Nouvelle Sauvegarde'}
          </span>
        </button>
      </div>

      <AnimatePresence>
        {backupStatus !== 'idle' && (
          <motion.div 
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className={cn(
              "p-4 rounded-2xl font-bold text-xs uppercase tracking-widest text-center",
              backupStatus === 'success' ? "bg-emerald-50 text-emerald-600 border border-emerald-100" : "bg-red-50 text-red-600 border border-red-100"
            )}
          >
            {backupStatus === 'success' ? 'La sauvegarde a été archivée avec succès dans votre coffre-fort numérique.' : 'Une erreur est survenue lors de la sauvegarde. Veuillez réessayer.'}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Info Card */}
      <div className="bg-primary-container/[0.03] border border-primary-container/10 p-6 rounded-[32px] flex items-start gap-4">
        <div className="bg-primary-container/10 p-3 rounded-2xl text-primary-container shrink-0">
          <ShieldCheck size={24} />
        </div>
        <div className="space-y-1">
          <h4 className="font-display font-bold text-on-surface">Chiffrement de bout en bout</h4>
          <p className="text-xs text-on-surface-variant leading-relaxed opacity-80">
            Toutes vos sauvegardes sont chiffrées avec AES-256 avant de quitter votre navigateur. 
            Aucune donnée en clair n'est stockée sur nos serveurs de sauvegarde. 
            Seul votre compte peut restaurer et déchiffrer ces informations.
          </p>
        </div>
      </div>

      {/* Backups List */}
      <div className="bg-white rounded-[40px] border border-outline-variant shadow-sm overflow-hidden">
        <div className="p-8 border-b border-outline-variant flex flex-col sm:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-3">
            <Clock className="text-secondary" size={24} />
            <h2 className="font-display font-bold text-xl">Historique des Archives</h2>
          </div>
          <div className="relative w-full sm:w-64">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant opacity-40" size={16} />
            <input 
              type="text"
              placeholder="Chercher type..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 bg-background border border-outline-variant rounded-xl text-sm focus:outline-none focus:border-primary-container transition-colors"
            />
          </div>
        </div>

        <div className="divide-y divide-outline-variant">
          {loading ? (
            <div className="p-20 text-center animate-pulse text-on-surface-variant font-bold uppercase text-[10px] tracking-widest">
              Consultation des archives sécurisées...
            </div>
          ) : filteredBackups.length === 0 ? (
            <div className="p-20 text-center space-y-4">
              <div className="w-16 h-16 bg-surface rounded-full flex items-center justify-center mx-auto text-on-surface-variant/20">
                <Database size={32} />
              </div>
              <p className="text-on-surface-variant text-sm font-medium">Aucune sauvegarde trouvée.</p>
            </div>
          ) : (
            filteredBackups.map((backup) => (
              <div key={backup.id} className="p-6 transition-colors hover:bg-background group">
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                  <div className="flex items-start gap-4">
                    <div className={cn(
                      "p-3 rounded-2xl flex items-center justify-center",
                      backup.autoGenerated ? "bg-secondary/10 text-secondary" : "bg-primary-container/10 text-primary-container"
                    )}>
                      {backup.autoGenerated ? <Clock size={20} /> : <ShieldCheck size={20} />}
                    </div>
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <h4 className="font-bold text-lg">{backup.type}</h4>
                        <span className={cn(
                          "px-2 py-0.5 rounded-md text-[8px] font-black uppercase tracking-widest border",
                          backup.autoGenerated ? "bg-secondary/5 text-secondary border-secondary/10" : "bg-primary-container/5 text-primary-container border-primary-container/10"
                        )}>
                          {backup.autoGenerated ? 'Auto' : 'Manuel'}
                        </span>
                      </div>
                      <div className="flex items-center gap-2 text-xs text-on-surface-variant">
                         <Clock size={12} />
                         {backup.timestamp?.toDate ? format(backup.timestamp.toDate(), "d MMMM yyyy 'à' HH:mm", { locale: fr }) : 'Date inconnue'}
                      </div>
                    </div>
                  </div>

                  <div className="flex flex-col items-end gap-2 w-full sm:w-auto">
                      <div className="flex items-center gap-2 w-full sm:w-auto">
                        <button 
                          onClick={() => handleRestore(backup)}
                          disabled={!!restoringId}
                          className={cn(
                            "flex-grow sm:flex-none flex items-center justify-center gap-2 px-6 py-3 rounded-xl text-xs font-bold uppercase tracking-widest transition-all",
                            restoringId === backup.id 
                              ? (restoreStatus === 'success' ? "bg-emerald-500 text-white" : 
                                 restoreStatus === 'error' ? "bg-red-500 text-white" :
                                 "bg-primary-container/10 text-primary-container")
                              : "bg-surface border border-outline-variant text-on-surface-variant hover:text-primary-container hover:bg-white shadow-sm"
                          )}
                        >
                          {restoringId === backup.id ? (
                            restoreStatus === 'success' ? <CheckCircle2 size={16} /> :
                            restoreStatus === 'error' ? <AlertTriangle size={16} /> :
                            <div className="w-4 h-4 border-2 border-primary-container/30 border-t-primary-container rounded-full animate-spin" />
                          ) : (
                            <RotateCcw size={16} />
                          )}
                          <span>
                            {restoringId === backup.id ? 
                             (restoreStatus === 'success' ? 'Restauration réussie' : 
                              restoreStatus === 'error' ? 'Échec' : 'Restauration...') : 
                             'Restaurer'}
                          </span>
                        </button>
                        <button 
                          onClick={() => handleDeleteBackup(backup.id)}
                          className="p-3 text-on-surface-variant hover:text-red-500 hover:bg-red-50 rounded-xl transition-all border border-transparent hover:border-red-100"
                        >
                          <Trash2 size={16} />
                        </button>
                      </div>
                      
                      <AnimatePresence>
                        {restoringId === backup.id && restoreStep && (
                          <motion.div 
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: 'auto' }}
                            exit={{ opacity: 0, height: 0 }}
                            className="w-full text-[10px] font-bold uppercase tracking-wider text-primary-container text-right overflow-hidden flex items-center justify-end gap-2"
                          >
                            <span className="animate-pulse">{restoreStep}</span>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                </div>
                
                {backup.payload && (
                  <div className="mt-4 flex items-center gap-2 p-2 bg-surface/50 rounded-lg border border-dashed border-outline-variant/50">
                    <CheckCircle2 size={12} className="text-secondary" />
                    <span className="text-[10px] font-mono opacity-50 truncate">Checksum: {backup.payload.substring(0, 32)}...</span>
                  </div>
                )}
              </div>
            ))
          )}
        </div>
      </div>
      
      {/* Warning */}
      <div className="p-6 bg-red-50 border border-red-100 rounded-[32px] flex items-start gap-4 shadow-sm shadow-red-500/5">
        <div className="p-3 bg-red-500/10 text-red-500 rounded-2xl">
          <AlertTriangle size={24} />
        </div>
        <div className="space-y-1">
          <h4 className="font-display font-bold text-red-900">Procédure de Restauration</h4>
          <p className="text-xs text-red-800 leading-relaxed opacity-80">
            La restauration de données est une opération critique. Assurez-vous de ne pas avoir de travaux non sauvegardés dans la session actuelle. 
            Nous vous conseillons de créer une sauvegarde manuelle juste avant toute restauration.
          </p>
        </div>
      </div>
    </div>
  );
}
