import { useState, useEffect } from 'react';
import { collection, query, where, orderBy, onSnapshot, addDoc, serverTimestamp, getDocs, deleteDoc, doc, writeBatch } from 'firebase/firestore';
import { db, auth } from '../lib/firebase';
import { decryptData, encryptData, encryptNumeric } from '../lib/encryption';
import { useCompany } from '../context/CompanyContext';
import { Database, Download, RotateCcw, Trash2, Clock, ShieldCheck, AlertTriangle, CheckCircle2, Search } from 'lucide-react';
import { format } from 'date-fns';
import { fr } from 'date-fns/locale';
import { motion, AnimatePresence } from 'motion/react';
import { cn } from '../lib/utils';

interface BackupRecord {
  id: string;
  type: string;
  payload: string;
  timestamp: any;
  autoGenerated: boolean;
  encrypted: boolean;
}

export default function Backups() {
  const { selectedCompany, revenues, detailedEntries } = useCompany();
  const [backups, setBackups] = useState<BackupRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [isBackingUp, setIsBackingUp] = useState(false);
  const [restoringId, setRestoringId] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    if (!auth.currentUser) return;

    const q = query(
      collection(db, 'backups'),
      where('userId', '==', auth.currentUser.uid),
      orderBy('timestamp', 'desc')
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      setBackups(snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as BackupRecord)));
      setLoading(false);
    });

    return () => unsubscribe();
  }, []);

  const handleManualBackup = async () => {
    if (!auth.currentUser || !selectedCompany) return;
    setIsBackingUp(true);

    try {
      const snapData = {
        companyId: selectedCompany.id,
        companyName: selectedCompany.name,
        revenues,
        detailedEntries,
        snapshotDate: new Date().toISOString()
      };

      const encryptedPayload = encryptData(snapData);

      await addDoc(collection(db, 'backups'), {
        type: 'MANUAL_FULL_SNAPSHOT',
        payload: encryptedPayload,
        userId: auth.currentUser.uid,
        timestamp: serverTimestamp(),
        autoGenerated: false,
        encrypted: true
      });

      alert('Sauvegarde manuelle réussie.');
    } catch (error) {
      console.error('Backup error:', error);
      alert('Erreur lors de la sauvegarde.');
    } finally {
      setIsBackingUp(false);
    }
  };

  const handleRestore = async (backup: BackupRecord) => {
    if (!auth.currentUser || !selectedCompany) return;
    
    const confirmRestore = confirm(
      "ATTENTION: La restauration remplacera vos données actuelles par celles de la sauvegarde. Cette action est irréversible. Voulez-vous continuer ?"
    );
    
    if (!confirmRestore) return;

    setRestoringId(backup.id);

    try {
      const data = decryptData<any>(backup.payload);
      if (!data) throw new Error('Impossible de décrypter la sauvegarde.');

      const batch = writeBatch(db);

      // 1. Clear existing revenues for this company
      const revSnap = await getDocs(query(
        collection(db, 'revenues'), 
        where('userId', '==', auth.currentUser.uid), 
        where('companyId', '==', selectedCompany.id)
      ));
      revSnap.docs.forEach(d => batch.delete(d.ref));

      // 2. Clear existing detailed entries
      const detSnap = await getDocs(query(
        collection(db, 'detailed_entries'), 
        where('userId', '==', auth.currentUser.uid), 
        where('companyId', '==', selectedCompany.id)
      ));
      detSnap.docs.forEach(d => batch.delete(d.ref));

      // 3. Add restored revenues
      if (data.revenues && Array.isArray(data.revenues)) {
        data.revenues.forEach((rev: any) => {
          const { id, ...cleanRev } = rev;
          const restoredRev = {
            ...cleanRev,
            revenue: encryptNumeric(cleanRev.revenue),
            userId: auth.currentUser!.uid,
            createdAt: serverTimestamp(),
            isEncrypted: true
          };
          const docRef = doc(collection(db, 'revenues'));
          batch.set(docRef, restoredRev);
        });
      }

      // 4. Add restored detailed entries
      if (data.detailedEntries && Array.isArray(data.detailedEntries)) {
        data.detailedEntries.forEach((entry: any) => {
          const { id, date, ...cleanEntry } = entry;
          
          const encryptedBreakdown: any = {};
          Object.entries(cleanEntry.breakdown || {}).forEach(([k, v]) => {
            encryptedBreakdown[k] = encryptNumeric(v as number);
          });

          const restoredEntry = {
            ...cleanEntry,
            breakdown: encryptedBreakdown,
            total: encryptNumeric(cleanEntry.total),
            userId: auth.currentUser!.uid,
            date: serverTimestamp(), // reset date to restore time
            isEncrypted: true
          };
          
          const docRef = doc(collection(db, 'detailed_entries'));
          batch.set(docRef, restoredEntry);
        });
      }

      await batch.commit();
      alert('Restauration terminée avec succès.');
    } catch (error) {
      console.error('Restore error:', error);
      alert('Erreur lors de la restauration.');
    } finally {
      setRestoringId(null);
    }
  };

  const handleDeleteBackup = async (id: string) => {
    if (!confirm('Supprimer cette sauvegarde définitivement ?')) return;
    try {
      await deleteDoc(doc(db, 'backups', id));
    } catch (error) {
      console.error('Delete error:', error);
    }
  };

  const filteredBackups = backups.filter(b => 
    b.type.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-8 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-6">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-secondary font-bold text-[10px] uppercase tracking-[0.2em]">
            <RotateCcw size={14} />
            <span>Sécurité & Intégrité</span>
          </div>
          <h1 className="font-display font-bold text-3xl sm:text-4xl text-on-surface">Sauvegardes & Restauration</h1>
          <p className="text-on-surface-variant text-sm font-sans opacity-70">
            Gérez vos archives chiffrées et recupérez vos données en cas de besoin.
          </p>
        </div>
        <button 
          onClick={handleManualBackup}
          disabled={isBackingUp}
          className="flex items-center gap-3 bg-primary-container text-white px-8 py-4 rounded-2xl font-bold hover:brightness-110 active:scale-95 transition-all shadow-xl shadow-primary-container/20 disabled:opacity-50"
        >
          {isBackingUp ? (
            <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
          ) : (
            <Download size={20} />
          )}
          <span>Nouvelle Sauvegarde</span>
        </button>
      </div>

      {/* Info Card */}
      <div className="bg-primary-container/[0.03] border border-primary-container/10 p-6 rounded-[32px] flex items-start gap-4">
        <div className="bg-primary-container/10 p-3 rounded-2xl text-primary-container shrink-0">
          <ShieldCheck size={24} />
        </div>
        <div className="space-y-1">
          <h4 className="font-display font-bold text-on-surface">Chiffrement de bout en bout</h4>
          <p className="text-xs text-on-surface-variant leading-relaxed opacity-80">
            Toutes vos sauvegardes sont chiffrées avec AES-256 avant de quitter votre navigateur. 
            Aucune donnée en clair n'est stockée sur nos serveurs de sauvegarde. 
            Seul votre compte peut restaurer et déchiffrer ces informations.
          </p>
        </div>
      </div>

      {/* Backups List */}
      <div className="bg-white rounded-[40px] border border-outline-variant shadow-sm overflow-hidden">
        <div className="p-8 border-b border-outline-variant flex flex-col sm:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-3">
            <Clock className="text-secondary" size={24} />
            <h2 className="font-display font-bold text-xl">Historique des Archives</h2>
          </div>
          <div className="relative w-full sm:w-64">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant opacity-40" size={16} />
            <input 
              type="text"
              placeholder="Chercher type..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 bg-background border border-outline-variant rounded-xl text-sm focus:outline-none focus:border-primary-container transition-colors"
            />
          </div>
        </div>

        <div className="divide-y divide-outline-variant">
          {loading ? (
            <div className="p-20 text-center animate-pulse text-on-surface-variant font-bold uppercase text-[10px] tracking-widest">
              Consultation des archives sécurisées...
            </div>
          ) : filteredBackups.length === 0 ? (
            <div className="p-20 text-center space-y-4">
              <div className="w-16 h-16 bg-surface rounded-full flex items-center justify-center mx-auto text-on-surface-variant/20">
                <Database size={32} />
              </div>
              <p className="text-on-surface-variant text-sm font-medium">Aucune sauvegarde trouvée.</p>
            </div>
          ) : (
            filteredBackups.map((backup) => (
              <div key={backup.id} className="p-6 transition-colors hover:bg-background group">
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                  <div className="flex items-start gap-4">
                    <div className={cn(
                      "p-3 rounded-2xl flex items-center justify-center",
                      backup.autoGenerated ? "bg-secondary/10 text-secondary" : "bg-primary-container/10 text-primary-container"
                    )}>
                      {backup.autoGenerated ? <Clock size={20} /> : <ShieldCheck size={20} />}
                    </div>
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <h4 className="font-bold text-lg">{backup.type}</h4>
                        <span className={cn(
                          "px-2 py-0.5 rounded-md text-[8px] font-black uppercase tracking-widest border",
                          backup.autoGenerated ? "bg-secondary/5 text-secondary border-secondary/10" : "bg-primary-container/5 text-primary-container border-primary-container/10"
                        )}>
                          {backup.autoGenerated ? 'Auto' : 'Manuel'}
                        </span>
                      </div>
                      <div className="flex items-center gap-2 text-xs text-on-surface-variant">
                         <Clock size={12} />
                         {backup.timestamp?.toDate ? format(backup.timestamp.toDate(), "d MMMM yyyy 'à' HH:mm", { locale: fr }) : 'Date inconnue'}
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 w-full sm:w-auto">
                    <button 
                      onClick={() => handleRestore(backup)}
                      disabled={!!restoringId}
                      className={cn(
                        "flex-grow sm:flex-none flex items-center justify-center gap-2 px-6 py-3 rounded-xl text-xs font-bold uppercase tracking-widest transition-all",
                        restoringId === backup.id 
                          ? "bg-primary-container/10 text-primary-container" 
                          : "bg-surface border border-outline-variant text-on-surface-variant hover:text-primary-container hover:bg-white shadow-sm"
                      )}
                    >
                      {restoringId === backup.id ? (
                        <div className="w-4 h-4 border-2 border-primary-container/30 border-t-primary-container rounded-full animate-spin" />
                      ) : (
                        <RotateCcw size={16} />
                      )}
                      <span>Restaurer</span>
                    </button>
                    <button 
                      onClick={() => handleDeleteBackup(backup.id)}
                      className="p-3 text-on-surface-variant hover:text-red-500 hover:bg-red-50 rounded-xl transition-all border border-transparent hover:border-red-100"
                    >
                      <Trash2 size={16} />
                    </button>
                  </div>
                </div>
                
                {backup.payload && (
                  <div className="mt-4 flex items-center gap-2 p-2 bg-surface/50 rounded-lg border border-dashed border-outline-variant/50">
                    <CheckCircle2 size={12} className="text-secondary" />
                    <span className="text-[10px] font-mono opacity-50 truncate">Checksum: {backup.payload.substring(0, 32)}...</span>
                  </div>
                )}
              </div>
            ))
          )}
        </div>
      </div>
      
      {/* Warning */}
      <div className="p-6 bg-red-50 border border-red-100 rounded-[32px] flex items-start gap-4 shadow-sm shadow-red-500/5">
        <div className="p-3 bg-red-500/10 text-red-500 rounded-2xl">
          <AlertTriangle size={24} />
        </div>
        <div className="space-y-1">
          <h4 className="font-display font-bold text-red-900">Procédure de Restauration</h4>
          <p className="text-xs text-red-800 leading-relaxed opacity-80">
            La restauration de données est une opération critique. Assurez-vous de ne pas avoir de travaux non sauvegardés dans la session actuelle. 
            Nous vous conseillons de créer une sauvegarde manuelle juste avant toute restauration.
          </p>
        </div>
      </div>
    </div>
  );
}
